# Generated by Django 4.1.6 on 2023-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLacuna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('ciudadNatal', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGym', models.CharField(max_length=60)),
                ('medalla', models.CharField(max_length=60)),
                ('tipoGym', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='nombre',
            new_name='nombrePokemon',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='tipo',
            new_name='tipoPokemon',
        ),
    ]
