# Generated by Django 4.1.6 on 2023-02-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLacuna', '0002_entrenador_gym_rename_nombre_pokemon_nombrepokemon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='ciudadNatal',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='entrenador',
            old_name='nombrePersona',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='nombreGym',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='gym',
            old_name='tipoGym',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='nombrePokemon',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='tipoPokemon',
            new_name='tipo',
        ),
    ]
